services:
  api-gateway:
    build: ./backend/services/api-gateway
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  auth-service:
    build: ./backend/services/auth-service
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development

  user-service:
    build: ./backend/services/user-service
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development

  post-service:
    build: ./backend/services/post-service
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=development

  feed-service:
    build: ./backend/services/feed-service
    ports:
      - "3004:3004"
    environment:
      - NODE_ENV=development

  media-service:
    build: ./backend/services/media-service
    ports:
      - "3005:3005"
    environment:
      - NODE_ENV=development

  notification-service:
    build: ./backend/services/notification-service
    ports:
      - "3006:3006"
    environment:
      - NODE_ENV=development